// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.Models;

namespace Server.Migrations
{
    [DbContext(typeof(AndjelaContext))]
    [Migration("20210908165407_V5")]
    partial class V5
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Server.Models.Film", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Godina")
                        .HasColumnType("int")
                        .HasColumnName("GODINA");

                    b.Property<string>("ImeRezisera")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("IMEREZISERA");

                    b.Property<string>("Naziv")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("NAZIVFILMA");

                    b.Property<string>("PrezimeRezisera")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("PREZIMEREZISERA");

                    b.Property<int?>("RedID")
                        .HasColumnType("int");

                    b.Property<string>("Tip")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("TIPFILMA");

                    b.Property<int>("Trajanje")
                        .HasColumnType("int")
                        .HasColumnName("TRAJANJEFILMA");

                    b.HasKey("ID");

                    b.HasIndex("RedID");

                    b.ToTable("FILM");
                });

            modelBuilder.Entity("Server.Models.Klub", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ime")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("IME");

                    b.Property<int>("MaksimalniBroj")
                        .HasColumnType("int")
                        .HasColumnName("MAKSIMALNIBROJ");

                    b.HasKey("ID");

                    b.ToTable("KLUB");
                });

            modelBuilder.Entity("Server.Models.Red", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("KlubID")
                        .HasColumnType("int");

                    b.Property<int>("MaxKapacitet")
                        .HasColumnType("int")
                        .HasColumnName("MAKSIMALNIKAPACITETREDA");

                    b.Property<string>("Tip")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("TIPREDA");

                    b.HasKey("ID");

                    b.HasIndex("KlubID");

                    b.ToTable("RED");
                });

            modelBuilder.Entity("Server.Models.Film", b =>
                {
                    b.HasOne("Server.Models.Red", "Red")
                        .WithMany("Filmovi")
                        .HasForeignKey("RedID");

                    b.Navigation("Red");
                });

            modelBuilder.Entity("Server.Models.Red", b =>
                {
                    b.HasOne("Server.Models.Klub", "Klub")
                        .WithMany("Redovi")
                        .HasForeignKey("KlubID");

                    b.Navigation("Klub");
                });

            modelBuilder.Entity("Server.Models.Klub", b =>
                {
                    b.Navigation("Redovi");
                });

            modelBuilder.Entity("Server.Models.Red", b =>
                {
                    b.Navigation("Filmovi");
                });
#pragma warning restore 612, 618
        }
    }
}
