// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.Models;

namespace Server.Migrations
{
    [DbContext(typeof(AndjelaContext))]
    [Migration("20210907181801_najboljiKlijentInit")]
    partial class najboljiKlijentInit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Server.Models.Film", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("KlubID")
                        .HasColumnType("int");

                    b.Property<int?>("RedID")
                        .HasColumnType("int");

                    b.Property<string>("imeRezisera")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("IMEREZISERA");

                    b.Property<string>("naziv")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("NAZIVFILMA");

                    b.Property<string>("prezimeRezisera")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("PREZIMEREZISERA");

                    b.Property<int>("sifra")
                        .HasColumnType("int")
                        .HasColumnName("SIFRA");

                    b.Property<string>("tip")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("TIPFILMA");

                    b.Property<int>("trajanje")
                        .HasColumnType("int")
                        .HasColumnName("TRAJANJEFILMA");

                    b.HasKey("ID");

                    b.HasIndex("KlubID");

                    b.HasIndex("RedID");

                    b.ToTable("FILM");
                });

            modelBuilder.Entity("Server.Models.Klub", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ime")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("IME");

                    b.Property<int>("maksimalniBroj")
                        .HasColumnType("int")
                        .HasColumnName("MAKSIMALNIBROJ");

                    b.Property<int>("trenutniBroj")
                        .HasColumnType("int")
                        .HasColumnName("TRENUTNIBROJ");

                    b.HasKey("ID");

                    b.ToTable("KLUB");
                });

            modelBuilder.Entity("Server.Models.Red", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("KlubID")
                        .HasColumnType("int");

                    b.Property<int>("maxKapacitet")
                        .HasColumnType("int")
                        .HasColumnName("MAKSIMALNIKAPACITETREDA");

                    b.Property<int>("redniBroj")
                        .HasColumnType("int")
                        .HasColumnName("REDNIBROJREDA");

                    b.Property<string>("tip")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("TIPREDA");

                    b.Property<int>("trKapacitet")
                        .HasColumnType("int")
                        .HasColumnName("TRENUTNIKAPACITET");

                    b.HasKey("ID");

                    b.HasIndex("KlubID");

                    b.ToTable("RED");
                });

            modelBuilder.Entity("Server.Models.Film", b =>
                {
                    b.HasOne("Server.Models.Klub", null)
                        .WithMany("Filmovi")
                        .HasForeignKey("KlubID");

                    b.HasOne("Server.Models.Red", null)
                        .WithMany("Filmovi")
                        .HasForeignKey("RedID");
                });

            modelBuilder.Entity("Server.Models.Red", b =>
                {
                    b.HasOne("Server.Models.Klub", null)
                        .WithMany("Redovi")
                        .HasForeignKey("KlubID");
                });

            modelBuilder.Entity("Server.Models.Klub", b =>
                {
                    b.Navigation("Filmovi");

                    b.Navigation("Redovi");
                });

            modelBuilder.Entity("Server.Models.Red", b =>
                {
                    b.Navigation("Filmovi");
                });
#pragma warning restore 612, 618
        }
    }
}
