INSERT [dbo].[KLUB] ([ID], [IME], [MAKSIMALNIBROJ]) VALUES (1, 'Klub 1', 5)
GO
INSERT [dbo].[KLUB] ([ID], [IME], [MAKSIMALNIBROJ]) VALUES (2, 'klub 2', 10)
GO
SET IDENTITY_INSERT [dbo].[KLUB] OFF
GO
